# This workflow installs builds Python wheels using cibuildwheel

name: Build Python Wheels
run-name: ${{ github.actor }} building Python Wheel

on:
  push:
    branches: [ "master" ]
    paths:
      - goopylib/**
      - src/**
      - binaries/**

  pull_request:
    branches: [ "master" ]
    paths:
      - goopylib/**
      - src/**
      - binaries/**

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
