# This workflow installs builds Python wheels using cibuildwheel

name: Build Python Wheels
run-name: ${{ github.actor }} building Python Wheel

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
    paths:
      - goopylib/**
      # - src/**
      - binaries/**
      - pyproject.toml
      - setup.py
      - tools/setup_extensions.py

  pull_request:
    branches: [ "master" ]
    paths:
      - goopylib/**
      # - src/**
      - binaries/**
      - pyproject.toml
      - setup.py
      - tools/setup_extensions.py

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BUILD: cp38-* pp38-*

        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
