# This workflow installs Python dependencies, build the required goopylib wheels and check them with Twine

name: Build Python Package from sdist
run-name: ${{ github.actor }} building Python Package from sdist

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel
        python -m pip install twine

    - name: Build Wheels
      run: |
        cibuildwheel --platform macos

    - name: Check Wheels
      run: | 
        twine check wheelhouse/*
